package org.example.myfarmbackend.services;

import net.datafaker.Faker;
import org.example.myfarmbackend.models.Animal;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.util.concurrent.atomic.AtomicBoolean;

@Service
public class DataGenerationService {

    private final AnimalService animalService;
    private final SimpMessagingTemplate messagingTemplate;
    private final AtomicBoolean isGenerating = new AtomicBoolean(false);
    private final Faker faker = new Faker();

    public DataGenerationService(AnimalService animalService, SimpMessagingTemplate messagingTemplate) {
        this.animalService = animalService;
        this.messagingTemplate = messagingTemplate;
    }

    public void startGenerating(long ownerId) {
        if (isGenerating.compareAndSet(false, true)) {
            generateDataLoop(ownerId);
        }
    }

    public void stopGenerating() {
        isGenerating.set(false);
    }

    @Async
    public void generateDataLoop(long ownerId) {
        String[] types = {"vaca", "porc", "gaina", "oaie", "capra", "cal"};
        String[] statuses = {"Sanatoasa", "Bolnava", "Gestanta", "Recuperare"};

        while (isGenerating.get()) {
            try {
                Thread.sleep(5000);

                Animal animal = new Animal();
                animal.setId(System.currentTimeMillis());
                animal.setName(faker.name().firstName());
                animal.setType(types[faker.random().nextInt(types.length)]);
                animal.setSex(faker.random().nextBoolean() ? "mascul" : "femela");
                animal.setAge(faker.random().nextInt(1, 10));
                animal.setStatus(statuses[faker.random().nextInt(statuses.length)]);
                animal.setLocation(faker.address().city());
                animal.setOwnerId(ownerId);
                animal.setObservations("Generated by Faker");

                Animal saved = animalService.addAnimal(animal);

                messagingTemplate.convertAndSend("/topic/animals", saved);

            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                break;
            }
        }
    }
}
